### ISSUE TITLE
Add method `overflowing_pow` for uints

### ISSUE THREAD

**Issue by mohanson** [cryptape/rust-numext#28]

**Comment by yangby-cryptape** [comment]
TODO:
- [ ] [`pub fn checked_pow(self, exp: u32) -> Option<u64>`](https://doc.rust-lang.org/std/primitive.u64.html#method.checked_pow)
- [ ] [`pub fn saturating_pow(self, exp: u32) -> u64`](https://doc.rust-lang.org/std/primitive.u64.html#method.saturating_pow)
- [ ] [`pub fn wrapping_pow(self, exp: u32) -> u64`](https://doc.rust-lang.org/std/primitive.u64.html#method.wrapping_pow)
- [ ] [`pub fn overflowing_pow(self, exp: u32) -> (u64, bool)`](https://doc.rust-lang.org/std/primitive.u64.html#method.overflowing_pow)
