### ISSUE TITLE
Take a very long time to wait result

### ISSUE THREAD

**Issue by mohanson** [cryptape/rust-numext#34]
```rs
use numext_fixed_uint::U4096;

fn main() {
    let a = U4096::from_dec_str("3930061525912861057173624287137506221892737197425280369698987").unwrap();
    let b = U4096::from_dec_str("57896044618658097711785492504343953926634992332820282019728792003956564819968").unwrap();
    println!("{}", &a * &a % b);
}
```

I have wait serveral minutes and finally I give up.

**Comment by yangby-cryptape** [comment]
https://github.com/cryptape/rust-numext/blob/1481b3db251267acdb7311bbf611f02ee6058f9c/constructor/src/fixed_uint/core/internal/private_ops.rs#L554-L564

The first `sub()` overflows without check.

**Comment by yangby-cryptape** [comment]
## Preliminaries

I use the max significant(highest) units (`u64` in this example) of both dividend and divisor to predict the quotient.
(This is why my `/` and `%` are fast than others similar crates)

To insure `remainder-part-of-full-dividend > ((divisor * quotient) << difference-of-digits)`, I do `divisor -= 1`.

## Why it hangs

In this example, `((divisor * quotient) << difference-of-digits)` is far small than `remainder-part-of-full-dividend` (borrow a `u64` from the higher unit), so `copy` is far bigger than `other`, so it hangs in that loop.
https://github.com/cryptape/rust-numext/blob/1481b3db251267acdb7311bbf611f02ee6058f9c/constructor/src/fixed_uint/core/internal/private_ops.rs#L560-L564

So, **the result will be right, but the computation will be very slow**.

## How to fix

It should not break the previous loop (estimate stage) too earlier, if borrow a higher unit (`else` part).
https://github.com/cryptape/rust-numext/blob/1481b3db251267acdb7311bbf611f02ee6058f9c/constructor/src/fixed_uint/core/internal/private_ops.rs#L518-L528
