### ISSUE TITLE
`attempt to add with overflow` happened in a % b

### ISSUE THREAD

**Issue by mohanson** [cryptape/rust-numext#36]
New bugs happened. 

```rs
use numext_fixed_uint::U4096;

fn main() {
    let a = U4096::from_dec_str("77207453359070457604620928442586248569527320043595348948921733518358535471105").unwrap();
    let b = U4096::from_dec_str("115792089237316195423570985008687907853269984665640564039457584007913129639936").unwrap();

    let r1 = &a * &a;
    println!("{}", r1);

    let r2 = r1 % b;
    println!("{}", r2);
}
```

```sh

thread 'test_state_work' panicked at 'attempt to add with overflow'
```

_Originally posted by @mohanson in https://github.com/cryptape/rust-numext/pull/35#issuecomment-476927254_

**Comment by mohanson** [comment]
Both happened in "v0.1.2" and  "fix-div-slow-bug" branch by @yangby-cryptape

**Comment by yangby-cryptape** [comment]
https://github.com/cryptape/rust-numext/blob/1481b3db251267acdb7311bbf611f02ee6058f9c/constructor/src/fixed_uint/core/internal/private_ops.rs#L536-L539

This impossible overflow was break by an old commit (that commit was squashed, so I cannot paste the link, that commit could estimate larger, so more code was required, if always doing estimate smaller, it can skip a lot of overflow).
