### ISSUE TITLE
convert u256 from str panic unexpected

### ISSUE THREAD

**Issue by boundless-forest** [cryptape/rust-numext#45]
Hi, 

I encounted a unexpected problem while converting type from `str` to `u256` using `numext-fixed-uint = "0.1.4"`.

A sample test example like this:

```rs
fn main() {
    let x = "0000000000000000000000000000000000000000000000000000000000000001";
    println!("x: {}", U256::from_hex_str(x).unwrap()); // panic

    let y = "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff";
    println!("y: {}", U256::from_hex_str(y).unwrap());  // ok

    let z = "f000000000000000000000000000000000000000000000000000000000000001";
    println!("z: {}", U256::from_hex_str(z).unwrap()); // ok
}
```

Panic output:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromStr(InvalidCharacter { chr: 48, idx: 0 })', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
panic happened alway when str parameter starts with `000..`

**Comment by chaoticlonghair** [comment]
This `panic` is in the way that was expected.

- Decimal numbers omit starting zeros is a common sense (except `0`).

- A non-zero number which starting with zeros, should be considered as a octal number in programming languages.
  It's also a common sense.

  Ref: [Octal - In Computers](https://en.wikipedia.org/wiki/Octal#In_computers)
